config/routes.rb
Rails.application.routes.draw do
  root 'books#index'
  resources :books do
    member do
      get :similar
    end
    collection do
      get :random, as: :random
    end
  end
  get 'home/index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
  has_many :books_genres, dependent: :delete_all
  has_many :genres, through: :books_genres
  has_one :book_embedding, dependent: :destroy

  validates :isbn, presence: true, uniqueness: true

  before_create do
    genres_string = genres.map(&:label).sort.join(',')
    string = <<-STRING
title: #{title} 
author: #{author} 
series: #{series}
description: #{description}
genres: #{genres_string}
    STRING

    body = {
      inputs: string,
      truncate: true
    }
    response = Faraday.post('http://localhost:8080/embed', body.to_json, 'Content-Type' => 'application/json')
    embedding = JSON.parse(response.body).first
    build_book_embedding(embedding: embedding)
  end
end

app/models/book_embedding.rb
class BookEmbedding < ApplicationRecord
  belongs_to :book
  has_neighbors :embedding

  def similar_books(limit: 15)
    scope = nearest_neighbors(:embedding, distance: "euclidean").limit(limit)

    book_ids = scope.pluck(:book_id)
    Book.where(id: book_ids)
  end
end

app/models/books_genre.rb
class BooksGenre < ApplicationRecord
  belongs_to :book
  belongs_to :genre
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :books_genres, dependent: :delete_all
  has_many :books, through: :books_genres
  validates :label, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: %i[ show edit update destroy ]

  # GET /books
  def index
    scope =
    if params[:q]
      Book.where("title LIKE ?", "%#{params[:q]}%").or(Book.where("author LIKE ?", "%#{params[:q]}%")).limit(100)
    else
      Book.all.limit(10)
    end
    @books = scope.includes(:genres)
  end

  def random
    @book = Book.order("RANDOM()").first
    redirect_to @book
  end

  # GET /books/1
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  def create
    @book = Book.new(book_params)

    if @book.save
      redirect_to @book, notice: "Book was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /books/1
  def update
    if @book.update(book_params)
      redirect_to @book, notice: "Book was successfully updated.", status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /books/1
  def destroy
    @book.destroy!
    redirect_to books_url, notice: "Book was successfully destroyed.", status: :see_other
  end

  def similar
    @books = BookEmbedding.find_by(book_id: params[:id]).similar_books.includes(:genres)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:title, :series, :author, :description, :language, :isbn, :page, :publish_date, :cover_url, :rating)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/books/_book.html.erb
<div id="<%= dom_id book %>">
  <h2><%= book.title %></h2>

  <p>
    <%= image_tag book.cover_url, width: 100, loading: :lazy %>
  </p>

  <p>
    <strong>Series:</strong>
    <%= book.series %>
  </p>

  <p>
    <strong>Author:</strong>
    <%= book.author %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= book.description %>
  </p>

  <p>
    <strong>Genre:</strong>
    <i>
      <%= book.genres.map(&:label).join(', ') %>
    </i>
  </p>

  <p>
    <strong>Language:</strong>
    <%= book.language %>
  </p>

  <p>
    <strong>Isbn:</strong>
    <%= book.isbn %>
  </p>

  <p>
    <strong>Page:</strong>
    <%= book.page %>
  </p>

  <p>
    <strong>Publish date:</strong>
    <%= book.publish_date %>
  </p>

  <p>
    <strong>Rating:</strong>
    <%= book.rating %> ⭐️
  </p>
</div>

app/views/books/_book_preview.html.erb
<article style="min-width: 10em">
  <header>
    <h2><%= link_to book.title, book_path(book), target: '_top' %></h2>
  </header>
  <p>
    <%= image_tag book.cover_url, width: 100, loading: :lazy %>
  </p>

  <p>
    <strong>Author:</strong>
    <%= book.author %>
  </p>
</article>

app/views/books/_form.html.erb
<%= form_with(model: book) do |form| %>
  <% if book.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% book.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :series, style: "display: block" %>
    <%= form.text_field :series %>
  </div>

  <div>
    <%= form.label :author, style: "display: block" %>
    <%= form.text_field :author %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :language, style: "display: block" %>
    <%= form.text_field :language %>
  </div>

  <div>
    <%= form.label :isbn, style: "display: block" %>
    <%= form.text_field :isbn %>
  </div>

  <div>
    <%= form.label :page, style: "display: block" %>
    <%= form.number_field :page %>
  </div>

  <div>
    <%= form.label :publish_date, style: "display: block" %>
    <%= form.date_field :publish_date %>
  </div>

  <div>
    <%= form.label :cover_url, style: "display: block" %>
    <%= form.text_field :cover_url %>
  </div>

  <div>
    <%= form.label :rating, style: "display: block" %>
    <%= form.text_field :rating %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing book</h1>

<%= render "form", book: @book %>

<br>

<div>
  <%= link_to "Show this book", @book %> |
  <%= link_to "Back to books", books_path %>
</div>

app/views/books/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Books</h1>
<small>
  Total: <%= Book.count %>
</small>

<div id="books">
  <% @books.each do |book| %>
    <%= render partial: 'book_preview', locals: { book: book } %>
  <% end %>
</div>

app/views/books/new.html.erb
<h1>New book</h1>

<%= render "form", book: @book %>

<br>

<div>
  <%= link_to "Back to books", books_path %>
</div>

app/views/books/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @book %>

<!--<div>-->
<!--  <%#= link_to "Edit this book", edit_book_path(@book) %> |-->
  <%#= link_to "Back to books", books_path %>

  <%#= button_to "Destroy this book", @book, method: :delete %>
<!--</div>-->

<h2 style="padding-top: 2em">Similar</h2>
<%= turbo_frame_tag 'similar', src: similar_book_path(@book), loading: :lazy do %>
  <progress max="100" value="0"></progress>
<% end %>

app/views/books/similar.html.erb
<%= turbo_frame_tag 'similar' do %>
  <div style="display: flex; flex-direction: row; flex-wrap: wrap">
    <% @books.each do |book| %>
      <%= render partial: 'book_preview', locals: { book: book } %>
    <% end %>
  </div>
<% end %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookNeighbor</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <header>
    <nav>
      <menu>
        <li style="margin: auto"><%= link_to "Home", books_path %></li>
        <li style="margin: auto"><%= link_to "Random", random_books_path %></li>
        <li>
          <%= form_tag books_path, method: :get, style: 'padding: 0' do %>
            <%= text_field_tag :q, params[:q] %>
            <%= submit_tag "Search", style: 'display: none' %>
          <% end %>
        </li>
      </menu>
    </nav>
  </header>
    <%= yield %>
  </body>
</html>